### ISSUE TITLE
@:nativeFunctionCode encountered types are not included in the output

### ISSUE THREAD

**Issue by fourst4r** [SomeRanDev/reflaxe.CPP#40]
The following code will not #include (or generate) the output files for `FooBar`.
```haxe
// FooBar.hx
@:valueType class FooBar {}
```
```haxe
// Main.hx
@:nativeFunctionCode("(void){type0}")
extern function void<T>(c:Class<T>):Void;

function main() {
    void(FooBar);
}
```

**Comment by SomeRanDev** [comment]
The good news is the #include is an easy fix. The bad news... is I'm not sure how to fix `FooBar` not being generated. I think that might be a Haxe bug(?)

Unfortunately, there's no way for me to add classes manually since Reflaxe works during the final phase of compilation (after typing and optimization). It might be worth adding this as an issue on the Haxe github. There are functions that take classes as arguments in JavaScript, so could use a Haxe/JS example?

**Comment by fourst4r** [comment]
Hmm, I don't think it's a Haxe bug, because the exact same code compiled with hxcpp will generate `FooBar`. Unless there is something I'm missing?

**Comment by SomeRanDev** [comment]
OHH you might be right! Give me a bit. 🤔

**Comment by SomeRanDev** [comment]
OKAY! I haven't tested it, but this should be fixed now! (It might have just been really simple and I am dumb lmao)

**Comment by fourst4r** [comment]
Yes! Whatever you did fixed it.
Thanks a bunch. 👍
